INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (1, '4', 'Jackson', '75884 CEDEX 18', false, 'Paris 18', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (2, '55', 'Shelley', '49804 CEDEX', false, 'Trélazé', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (3, '31540', 'Twin Pines', '85708 CEDEX', false, 'Pouzauges', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (4, '7239', 'Fairview', '54021 CEDEX', false, 'Nancy', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (5, '138', 'Rusk', '83613 CEDEX', false, 'Fréjus', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (6, '2721', 'Granby', '84404 CEDEX', false, 'Apt', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (7, '2', 'Messerschmidt', '94675 CEDEX', false, 'Charenton-le-Pont', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (8, '1538', 'Hanson', '29399 CEDEX', false, 'Quimperlé', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (9, '69156', 'Monica', '64039 CEDEX', false, 'Pau', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (10, '336', 'Alpine', '92684 CEDEX', false, 'Levallois-Perret', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (11, '33', 'Lakewood', '51086 CEDEX', false, 'Reims', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (12, '5', 'Lighthouse Bay', 'M34', false, 'Denton', 'United Kingdom');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (13, '9856', 'Clove', 'BD23', false, 'Thorpe', 'United Kingdom');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (14, '13317', 'Steensland', '89010 CEDEX', false, 'Auxerre', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (15, '08', 'Westerfield', '42304 CEDEX', false, 'Roanne', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (16, '3905', 'Village', '51064 CEDEX', false, 'Reims', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (17, '462', 'Sycamore', '24111 CEDEX', false, 'Bergerac', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (18, '40410', 'Goodland', '61304 CEDEX', false, 'L''Aigle', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (19, '9257', 'Grover', '68064 CEDEX 3', false, 'Mulhouse', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (20, '1', 'Prairieview', '75817 CEDEX 17', false, 'Paris 17', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (21, '0', 'Dexter', '94657 CEDEX', false, 'Thiais', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (22, '85726', 'Golf', '74154 CEDEX', false, 'Rumilly', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (23, '687', 'Roth', '95334 CEDEX', false, 'Domont', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (24, '2', 'Homewood', 'SN13', false, 'Ashley', 'United Kingdom');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (25, '528', 'Sutherland', '17014 CEDEX 1', false, 'La Rochelle', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (26, '4117', 'Kipling', '09123', false, 'Chemnitz', 'Germany');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (27, '52282', 'Algoma', '44966 CEDEX 9', false, 'Nantes', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (28, '09844', 'Clemons', '66119', false, 'Saarbrücken', 'Germany');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (29, '604', 'Dottie', '35164 CEDEX', false, 'Montfort-sur-Meu', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (30, '18', 'Granby', '06116 CEDEX', false, 'Le Cannet', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (31, '8075', 'Thierer', '77246 CEDEX', false, 'Cesson', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (32, '6219', 'Dexter', '44945 CEDEX 9', false, 'Nantes', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (33, '298', 'Hazelcrest', '13538 CEDEX', false, 'Saint-Rémy-de-Provence', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (34, '007', 'Pawling', '20174 CEDEX 1', false, 'Ajaccio', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (35, '84163', 'Park Meadow', '34536 CEDEX', false, 'Béziers', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (36, '266', 'Eastlawn', '62259 CEDEX', false, 'Hénin-Beaumont', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (37, '3755', 'Bartelt', '95109 CEDEX', false, 'Argenteuil', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (38, '1196', 'Elka', '25215 CEDEX', false, 'Montbéliard', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (39, '25057', 'Iowa', '77544 CEDEX', false, 'Savigny-le-Temple', 'France');
INSERT INTO address (id_address, number, street, zipcode, soft_delete, city, country) VALUES (40, '79', 'Hoard', '83953 CEDEX', false, 'La Garde', 'France');
