/* INSERT 45 photo_products (36 cases & 9 accessories */

INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(1, 'https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_a52_blanc_128go_t2102234943937A_125603892.jpg', 1);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(2, 'https://static.s-sfr.fr/media/mobile/uc/device/ktmxcwj6/iphone13-face-red-162x320.jpg?ts=1631883629222', 2);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(3, 'https://bsimg.nl/images/nokia-g50-128gb-blauw_1.jpg/VPPfXHa6R-FJAlGbDi446wWmR1s%3D/fit-in/771x1200/filters%3Aformat%28webp%29%3Aupscale%28%29', 3);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(4, 'https://cdn.lesnumeriques.com/optim/product/63/63845/134f4cbc-a74-5g_png__450_400.webp', 4);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(5, 'https://proxymedia.woopic.com/api/v1/images/1618%2Fedithor%2Fterminaux%2Fxiaomi_12_5g_gris_02_621f91c8e58d76540b50bd92_621f8d42e58d76540b50bd8d.png?format=504x504&saveas=png&saveasquality=85', 5);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(6, 'https://proxymedia.woopic.com/api/v1/images/1618%2Fedithor%2Fterminaux%2F636x900-Negroni_black_name_render-img1_623c447e5223da5b93b0f2ca.jpg?format=504x504&saveas=jpg&saveasquality=85', 6);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(7, 'https://proxymedia.woopic.com/api/v1/images/1618%2Fedithor%2Fterminaux%2F636x900-google-pixel-6-noir-img1_61f8df5230ee0236ac664c96.png?format=504x504&saveas=png&saveasquality=85', 7);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(8, 'https://fr.shopping.rakuten.com/photo/2044996326.jpg', 8);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(9, 'https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_s20fe_4g_bleu_t2009234875028A_125648893.jpg', 9);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(10, 'https://static.fnac-static.com/multimedia/Images/FR/MDM/b7/fe/06/17235639/1540-1/tsp20220611102212/Smartphone-Huawei-Nova-8i-6-67-128-Go-Double-SIM-Argent.jpg', 10);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(11, 'https://fr.moviles.com/fotos/motorola-moto-e20-94506-g.jpg', 11);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(12, 'https://fr.shopping.rakuten.com/photo/1463392947.jpg', 12);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(13, 'https://static.fnac-static.com/multimedia/Images/FR/MDM/ef/87/a0/10520559/1540-1/tsp20220110182119/Smartphone-Sony-Xperia-XZ3-Double-SIM-64-Go-Vert.jpg', 13);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(14, 'https://m.media-amazon.com/images/I/61MwFMH84WL._AC_SL1500_.jpg', 37);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(15, 'https://m.media-amazon.com/images/I/61YI6ygBmUL._AC_SL1500_.jpg', 38);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(16, 'https://m.media-amazon.com/images/I/71BYKFrlL+L._AC_SL1500_.jpg', 39);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(17, 'https://m.media-amazon.com/images/I/61nzQ0Co0wL._AC_SL1000_.jpg', 40);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(18, 'https://m.media-amazon.com/images/I/61Gj7P7JBJS._AC_SL1500_.jpg', 41);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(19, 'https://m.media-amazon.com/images/I/51x2CMOs-dS._AC_SL1500_.jpg', 42);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(20, 'https://m.media-amazon.com/images/I/61ZI269dCvL._AC_SL1500_.jpg', 43);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(21, 'https://m.media-amazon.com/images/I/412Oia+sVbL._AC_.jpg', 44);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(22, 'https://m.media-amazon.com/images/I/71xKRYX7Y6S._AC_SL1500_.jpg', 45    );
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(23, 'https://m.media-amazon.com/images/I/61x-bnwpUfL._AC_SX522_.jpg', 23);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(24, 'https://m.media-amazon.com/images/I/816FlvGqwKL._AC_SX522_.jpg', 24);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(25, 'https://m.media-amazon.com/images/I/713XCa7WneS._AC_SX522_.jpg', 25);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(26, 'https://m.media-amazon.com/images/I/61qfOHeMXLL._AC_SX522_.jpg', 26);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(27, 'https://m.media-amazon.com/images/I/61EEgsjsYDL._AC_SX679_.jpg', 27);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(28, 'https://m.media-amazon.com/images/I/61NksQS6LML._AC_SX522_.jpg', 28);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(29, 'https://images-eu.ssl-images-amazon.com/images/I/61gnLelc9NL.__AC_SX300_SY300_QL70_ML2_.jpg', 29);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(30, 'https://m.media-amazon.com/images/I/51o-d8yllxL._AC_SX522_.jpg', 30);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(31, 'https://m.media-amazon.com/images/I/61Wlj45fRSL._AC_SX522_.jpg', 31);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(32, 'https://m.media-amazon.com/images/I/816kYygQ3cL._AC_SX522_.jpg', 32);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(33, 'https://m.media-amazon.com/images/I/81+nm-GPOGL._AC_SX522_.jpg', 33);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(34, 'https://m.media-amazon.com/images/I/71fjDfjUTsL._AC_SX522_.jpg', 34);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(35, 'https://m.media-amazon.com/images/I/71au11apobL._AC_SX522_.jpg', 35);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(36, 'https://m.media-amazon.com/images/I/61McGIBZdyL._AC_SX522_.jpg', 36);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(37, 'https://m.media-amazon.com/images/I/71I5fLJ0I3L._AC_SX522_.jpg', 14);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(38, 'https://m.media-amazon.com/images/I/81WDeQ3McoL._AC_SX522_.jpg', 15);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(39, 'https://m.media-amazon.com/images/I/815C7z3p7UL._AC_SX522_.jpg', 16);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(40, 'https://m.media-amazon.com/images/I/61RWqR9-LIL._AC_SX522_.jpg', 17);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(41, 'https://m.media-amazon.com/images/I/51uKaUVDi0L._AC_SX522_.jpg', 18);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(42, 'https://m.media-amazon.com/images/I/81TafkyWDtL._AC_SX522_.jpg', 19);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(43, 'https://m.media-amazon.com/images/I/61JOrmINNAL._AC_SX522_.jpg', 20);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(44, 'https://m.media-amazon.com/images/I/61Oz2lEEGyS._AC_SX522_.jpg', 21);
INSERT INTO public.photo_products
(id_photo_product, url_photo, id_product)
VALUES(45, 'https://m.media-amazon.com/images/I/71omd5y5YxL._AC_SX522_.jpg', 22);
